.PHONY: clean All

All:
	@echo "----------Building project:[ Hollow-knight-src - Debug ]----------"
	@cd "Hollow-knight-src" && "$(MAKE)" -f  "Hollow-knight-src.mk" && "$(MAKE)" -f  "Hollow-knight-src.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Hollow-knight-src - Debug ]----------"
	@cd "Hollow-knight-src" && "$(MAKE)" -f  "Hollow-knight-src.mk" clean
